
INSERT INTO STUDENTS (id, first_name, last_name, date_of_birth, email) VALUES 
					 (1, 'Ashley', 'Miller', '1999-12-01', 'ashleymiller@gmail.com');

INSERT INTO STUDENTS (id, first_name, last_name, date_of_birth, email) VALUES 
				 	 (2, 'Julia', 'Lopez', '1999-08-25', 'julialopez@gmail.com');
				 	 
INSERT INTO STUDENTS (id, first_name, last_name, date_of_birth, email) VALUES 
					 (3, 'Eric', 'Smith', '2002-03-15', 'ericsmith@gmail.com');

INSERT INTO STUDENTS (id, first_name, last_name, date_of_birth, email) VALUES 
				 	 (4, 'Joel', 'Hernandez', '2001-10-12', 'jhernandez@gmail.com');
				 	 
INSERT INTO STUDENTS (id, first_name, last_name, date_of_birth, email) VALUES 
				 	 (5, 'Chelsey', 'Woods', '1999-06-12', 'woordsc@gmail.com');

INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (1, 'CODE REVIEW', 'ALICE', 'PENDING');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (2, 'DESIGN MOCKUPS', 'BOB', 'COMPLETED');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (3, 'WRITE DOCUMENTATION', 'CHARLIE', 'IN PROGRESS');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (4, 'DEPLOY APPLICATION', 'DANA', 'ON HOLD');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (5, 'DATABASE MIGRATION', 'FRANK', 'CANCELLED');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (6, 'ORDER SERVICE', 'PRASANNA', 'COMPLETED');

-- Insert data into the COURSE table
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(1, 'JAVA', '5.MONTHS', 25000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(2, 'PYTHON', '4.MONTHS', 23000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(3, 'JAVASCRIPT', '3.MONTHS', 9000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(4, 'REACTJS', '1.MONTHS', 10000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(5, 'NODEJS', '2.MONTHS', 12000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(6, 'SQL', '2.MONTHS', 9000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(7, 'ANGULAR', '3.MONTHS', 18000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(8, 'MERNSTACK', '5.MONTHS', 22000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(9, 'ORACLEDBA', '5.MONTHS', 17000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(10, 'SAP', '5.MONTHS', 26000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(11, 'HTLL,CSS', '3.MONTHS', 8000.00);
