INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (1, 'CODE REVIEW', 'ALICE', 'PENDING');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (2, 'DESIGN MOCKUPS', 'BOB', 'COMPLETED');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (3, 'WRITE DOCUMENTATION', 'CHARLIE', 'IN PROGRESS');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (4, 'DEPLOY APPLICATION', 'DANA', 'ON HOLD');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (5, 'DATABASE MIGRATION', 'FRANK', 'CANCELLED');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (6, 'ORDER SERVICE', 'PRASANNA', 'COMPLETED');
