

INSERT INTO STUDENTS (id, first_name, last_name, date_of_birth, email) VALUES 
					 (1, 'Ashley', 'Miller', '1999-12-01', 'ashleymiller@gmail.com');

INSERT INTO STUDENTS (id, first_name, last_name, date_of_birth, email) VALUES 
				 	 (2, 'Julia', 'Lopez', '1999-08-25', 'julialopez@gmail.com');
				 	 
INSERT INTO STUDENTS (id, first_name, last_name, date_of_birth, email) VALUES 
					 (3, 'Eric', 'Smith', '2002-03-15', 'ericsmith@gmail.com');

INSERT INTO STUDENTS (id, first_name, last_name, date_of_birth, email) VALUES 
				 	 (4, 'Joel', 'Hernandez', '2001-10-12', 'jhernandez@gmail.com');
				 	 
INSERT INTO STUDENTS (id, first_name, last_name, date_of_birth, email) VALUES 
				 	 (5, 'Chelsey', 'Woods', '1999-06-12', 'woordsc@gmail.com');


INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(1, 'JAVA', '5.MONTHS', 25000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(2, 'PYTHON', '4.MONTHS', 23000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(3, 'JAVASCRIPT', '3.MONTHS', 9000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(4, 'REACTJS', '1.MONTHS', 10000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(5, 'NODEJS', '2.MONTHS', 12000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(6, 'SQL', '2.MONTHS', 9000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(7, 'ANGULAR', '3.MONTHS', 18000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(8, 'MERNSTACK', '5.MONTHS', 22000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(9, 'ORACLEDBA', '5.MONTHS', 17000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(10, 'SAP', '5.MONTHS', 26000.00);
INSERT INTO COURSE(ID, COURSE_NAME, COURSE_DURATION, COURSE_FEE) 
VALUES(11, 'HTLL,CSS', '3.MONTHS', 8000.00);


INSERT INTO COURSE_DETAILS (ID, COURSE_NAME, COURSE_DURIATION, COURSE_PRICE) VALUES 
					 (1, 'JAVA FULL STACK', '6 MONTHS', 22000);

INSERT INTO COURSE_DETAILS (ID, COURSE_NAME, COURSE_DURIATION, COURSE_PRICE) VALUES 
				 	 (2, 'PYTHON FULL STACK', '6 MONTHS', 20000);
				 	 
INSERT INTO COURSE_DETAILS (ID, COURSE_NAME, COURSE_DURIATION, COURSE_PRICE) VALUES 
					 (3, 'DEVOPS', '5 MONTHS', 15000);

INSERT INTO COURSE_DETAILS (ID, COURSE_NAME, COURSE_DURIATION, COURSE_PRICE) VALUES 
				 	 (4, 'POWERBI', '3 MONTHS', 15000);
				 	 
INSERT INTO COURSE_DETAILS (ID, COURSE_NAME, COURSE_DURIATION, COURSE_PRICE ) VALUES 
				 	 (5, 'AWS', '6 MONTHS', 18000);


INSERT INTO TOPICS (ID, TOPIC_NAME, TOPIC_AUTHOR, TOPIC_DESCRIPTION, TOPIC_STATUS) VALUES
                     (1, 'SAVITRI', 'NAG ASWIN', 'It is a Biopic of Savitri', 'UPDATED');
INSERT INTO TOPICS (ID, TOPIC_NAME, TOPIC_AUTHOR, TOPIC_DESCRIPTION, TOPIC_STATUS) VALUES
                     (2, 'JAVA', 'JAMES GOSLING', 'It is a programming language', 'UPDATED');
INSERT INTO TOPICS (ID, TOPIC_NAME, TOPIC_AUTHOR, TOPIC_DESCRIPTION, TOPIC_STATUS) VALUES
                     (3, 'PYTHON', 'GUIDO VAN ROSSUM', 'It is a programming language', 'UPDATED');
INSERT INTO TOPICS (ID, TOPIC_NAME, TOPIC_AUTHOR, TOPIC_DESCRIPTION, TOPIC_STATUS) VALUES
                     (4, 'C LANGUAGE', 'DENNIS RITCHIE', 'It is a programming language', 'UPDATED');


INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (1, 'CODE REVIEW', 'ALICE', 'PENDING');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (2, 'DESIGN MOCKUPS', 'BOB', 'COMPLETED');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (3, 'WRITE DOCUMENTATION', 'CHARLIE', 'IN PROGRESS');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (4, 'DEPLOY APPLICATION', 'DANA', 'ON HOLD');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (5, 'DATABASE MIGRATION', 'FRANK', 'CANCELLED');
INSERT INTO TASKDETAILS (ID, TASK_NAME, CREATED_BY, TASK_STATUS)
VALUES (6, 'ORDER SERVICE', 'PRASANNA', 'COMPLETED');

INSERT INTO COURSEDETAILS(ID, COURSE_NAME, COURSE_DESCRIPTION, COURSE_INSTRUCTOR)
VALUES(1, 'Web developemnt', 'creating web pages', 'john doe');

INSERT INTO COURSEDETAILS(ID, COURSE_NAME, COURSE_DESCRIPTION, COURSE_INSTRUCTOR)
VALUES(2, 'AWS', 'Cloud Based Programming', 'maya');

INSERT INTO COURSEDETAILS(ID, COURSE_NAME, COURSE_DESCRIPTION, COURSE_INSTRUCTOR)
VALUES(3, 'Python Scripting', 'Scripting language', 'shyam');

INSERT INTO COURSEDETAILS(ID, COURSE_NAME, COURSE_DESCRIPTION, COURSE_INSTRUCTOR)
VALUES(4, 'Java programming', 'Secure programming lanugage', 'Lio');

INSERT INTO TOPIC_LIST (ID, TOPIC_CATEGEORY, TOPIC_TITLE, TOPIC_CONCEPT, TOPIC_STATUS, STARTING_DATE, COMPLETION_DATE) 
VALUES (1, 'TECHNOLOGY', 'JAVA', 'OOPS', 'COMPLETED', '2024-11-24', '2024-11-30');

INSERT INTO TOPIC_LIST (ID, TOPIC_CATEGEORY, TOPIC_TITLE, TOPIC_CONCEPT, TOPIC_STATUS, STARTING_DATE, COMPLETION_DATE) 
VALUES (2, 'TECHNOLOGY', 'JAVA', 'LOOPS', 'COMPLETED', '2024-11-12', '2024-11-14');

INSERT INTO TOPIC_LIST (ID, TOPIC_CATEGEORY, TOPIC_TITLE, TOPIC_CONCEPT, TOPIC_STATUS, STARTING_DATE, COMPLETION_DATE) 
VALUES (3, 'TECHNOLOGY', 'JAVA', 'CONDITIONS', 'COMPLETED', '2024-11-16', '2024-11-19');

INSERT INTO ENROLLCOURSE(id, course_name, course_username, course_password, course_duration) VALUES 
					 (1, 'aws','Harsha_sree','Harsha@143','3 months');

INSERT INTO ENROLLCOURSE(id, course_name, course_username, course_password, course_duration) VALUES 
				 	 (2, 'java', 'Reva_sree','Revasree@143','6 months');
				 	 
INSERT INTO ENROLLCOURSE(id, course_name, course_username, course_password, course_duration) VALUES 
					 (3, 'python', 'Honey', 'Honey@143','4 months');
					 
INSERT INTO users (id, username, password, email)
	VALUES (1, 'Nandini', 'nandhu123', 'nandininandu@gmail.com');

INSERT INTO users (id, username, password, email) 
	VALUES (2, 'Ramya', 'ramya456', 'athurramya654@gmail.com');

INSERT INTO users (id, username, password, email) 
	VALUES (3, 'Poojitha', 'pooji789', 'bollupoojitha@gmail.com');
