INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER,USER_ADDRESS) 
VALUES (1, 'THARUN', 'THARUN@123', 'ARJUNSHARMA@GMAIL.COM', '9876543210', 'SOFTWARE ENGINEER', '2003-03-21', 'MALE', 'BENGALURU');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER,USER_ADDRESS) 
VALUES (2, 'PRIYAVERMA', 'PRIYASECURE!', 'PRIYAVERMA@GMAIL.COM', '9123456789', 'HARDWARE ENGINEER', '1990-08-25', 'FEMALE', 'HYDERABAD');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER, USER_ADDRESS) 
VALUES (3, 'RAHULGUPTA', 'RAHUL@2024', 'RAHULGUPTA@GMAIL.COM', '9234567890', 'SOFTWARE DEVELOPER', '1992-03-10', 'MALE', 'CHENNAI');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER, USER_ADDRESS) 
VALUES (4, 'KAVYANNAIR', 'KAVYAPASS1', 'KAVYANNAIR@GMAILCOM', '9345678901', 'SYSTEM ARCHITECT', '1998-01-15', 'FEMALE', 'MUMBAI');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER, USER_ADDRESS) 
VALUES (5, 'AMITSINGH', 'AMITSECURE#99', 'AMITSINGH@GMAIL.COM', '9542243682', 'NETWORK ENGINEER', '2003-03-21', 'MALE', 'DELHI');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER, USER_ADDRESS) 
VALUES (6, 'SWATIIYER', 'SWATIPASS456', 'SWATIIYER@GMAILCOM', '9567890123', 'HARDWARE SPECIALIST', '1994-07-30', 'FEMALE', 'BENGALURU');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER, USER_ADDRESS) 
VALUES (7, 'VISHALRAO', 'VISHAL@ENGINEER', 'VISHALRAO@GMAILCOM', '9678901234', 'SOFTWARE TESTER', '1991-09-17', 'MALE', 'HYDERABAD');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER, USER_ADDRESS) 
VALUES (8, 'ANANYAMENON', 'ANANYA@1234', 'ANANYAMENON@GMAIL.COM', '9789012345', 'SOFTWARE ENGINEER', '1999-12-05', 'FEMALE', 'MUMBAI');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER, USER_ADDRESS) 
VALUES (9, 'MANISHPATIL', 'MANISH123', 'MANISHPATIL@GMAIL.COM', '9890123456', 'HARDWARE ENGINEER', '1987-06-21', 'MALE', 'DELHI');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER, USER_ADDRESS) 
VALUES (10, 'SNEHAREDDY', 'SNEHAREDDY!', 'SNEHAREDDY@GMAIL.COM', '9901234567', 'SYSTEM ANALYST', '1996-03-13', 'FEMALE', 'BENGALURU');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER, USER_ADDRESS) 
VALUES (11, 'ADITYAMUKHERJEE', 'ADITYASECURE@!', 'ADITYAMUKHERJEE@GMAIL.COM', '9120123456', 'HARDWARE ARCHITECT', '1989-10-10', 'MALE', 'HYDERABAD');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER, USER_ADDRESS) 
VALUES (12, 'MEGHAKAPOOR', 'MEGHAPASS', 'MEGHAKAPOOR@GMAIL.COM', '9231234567', 'SOFTWARE ENGINEER', '1993-02-08', 'FEMALE', 'CHENNAI');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER, USER_ADDRESS) 
VALUES (13, 'ROHITMEHRA', 'ROHIT@PASSWORD', 'ROHITMEHRA@GMAIL.COM', '9340123456', 'SOFTWARE DEVELOPER', '1997-05-18', 'MALE', 'PUNE');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER, USER_ADDRESS) 
VALUES (14, 'DEEPASHETTY', 'DEEPASECURE!', 'DEEPASHETTY@GMAIL.COM', '9456123456', 'NETWORK ENGINEER', '1994-10-30', 'FEMALE', 'CHENNAI');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER, JOB_ROLE, DATE_OF_BIRTH, GENDER, USER_ADDRESS) 
VALUES (15, 'THARUN KUMAR', 'THARUN#46', 'THAARUNKUMAR@GMAIL.COM', '9345123456', 'SOFTWARE ENGINEER', '1986-07-09', 'MALE', 'BENGALURU');
